/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  // Set in Webflow Cloud → Environment variables (not committed to git).
  MAILERLITE_API_KEY?: string;
  MAILERLITE_GROUP_ID?: string;
}
