"use client";
import * as React from "react";
const NotSupported = React.forwardRef(function NotSupported(
  { _atom = "" },
  ref
) {
  // Webflow builtins DevLink can't render (Lottie animations, CMS Collection
  // Lists, etc.) render nothing instead of a visible placeholder message.
  // NOTE: this file is generated by `webflow devlink sync` and will be
  // overwritten on the next sync — re-apply this change if you re-sync.
  return null;
});
export default NotSupported;
